conf.py:
  copyright: 2015
  project: Calendar Base introduction
  version: 1.0
  release: 1.0.0
  latex_documents:
  - - Index
    - cal.tex
    - Calendar Base introduction
    - Mario Matzulla
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
