<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2013-02-27 09:31

$extensionClassesPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('t3_less') . 'Classes/';

return array(
	'DG\T3Less\Controller\BaseController' => $extensionClassesPath . 'Controller/BaseController.php',
    'DG\T3Less\Controller\LessPhpController' => $extensionClassesPath . 'Controller/LessPhpController.php',
	'DG\T3Less\Controller\LessJsController' => $extensionClassesPath . 'Controller/LessJsController.php',
	'DG\T3Less\Controller\LessJsNodeController' => $extensionClassesPath . 'Controller/LessJsNodeController.php',
	'DG\T3Less\Utility\Utilities' => $extensionClassesPath . 'Utility/Utilities.php',
);
?>