# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 1997-2015
  project: Core ChangeLog
  version: 7
  release: 7
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3api:
    - http://docs.typo3.org/typo3cms/CoreApiReference/
    - null
...
