<?php
return array(
	'BE' => array(
		'debug' => FALSE,
		'explicitADmode' => 'explicitAllow',
		'installToolPassword' => '$P$CtAODkhqp7cSHWHDMottvqytJsdf6b0',
		'loginSecurityLevel' => 'rsa',
		'versionNumberInFilename' => '0',
	),
	'DB' => array(
		'database' => 'loop_base',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => 'localhost',
		'password' => '1337mysql',
		'socket' => '',
		'username' => 'loop',
	),
	'EXT' => array(
		'extConf' => array(
			'adodb' => 'a:0:{}',
			'ajaxpagepreloader' => 'a:0:{}',
			'autoloader' => 'a:0:{}',
			'browser' => 'a:16:{s:13:"browserEngine";s:24:"Engine 5.x (recommended)";s:22:"browserEngineIndicator";s:17:"Off (recommended)";s:17:"external_links_01";s:1:"0";s:8:"LLstatic";s:6:"German";s:17:"external_links_02";s:1:"0";s:8:"drs_mode";s:18:"Don\'t log anything";s:28:"drs_pageNotFoundOnCHashError";s:1:"1";s:27:"drs_cHashExcludedParameters";s:1:"1";s:17:"external_links_03";s:1:"0";s:15:"showSampleTasks";s:1:"0";s:17:"external_links_04";s:1:"0";s:12:"updateWizard";s:1:"0";s:18:"updateWizardEnable";s:1:"0";s:9:"currentIP";s:1:"0";s:22:"updateWizardAllowedIPs";s:20:"127.0.0.1, 127.0.0.2";s:17:"external_links_05";s:1:"0";}',
			'browser_manual_en' => 'a:0:{}',
			'calendarize' => 'a:2:{s:19:"disableDefaultEvent";s:1:"0";s:21:"frequencyLimitPerItem";s:3:"300";}',
			'calendarize_news' => 'a:0:{}',
			'camaliga' => 'a:2:{s:12:"categoryMode";s:1:"1";s:14:"extendedFields";s:0:"";}',
			'cb_indexedsearch_autocomplete' => 'a:0:{}',
			'cb_newscal' => 'a:0:{}',
			'compatibility6' => 'a:0:{}',
			'cps_devlib' => 'a:0:{}',
			'cps_searchhighlight' => 'a:0:{}',
			'cps_tcatree' => 'a:0:{}',
			'crawler' => 'a:15:{s:9:"sleepTime";s:4:"1000";s:16:"sleepAfterFinish";s:2:"10";s:11:"countInARun";s:3:"100";s:14:"purgeQueueDays";s:2:"14";s:12:"processLimit";s:1:"1";s:17:"processMaxRunTime";s:3:"300";s:14:"maxCompileUrls";s:5:"10000";s:12:"processDebug";s:1:"0";s:16:"crawlHiddenPages";s:1:"0";s:7:"phpPath";s:12:"/usr/bin/php";s:14:"enableTimeslot";s:1:"1";s:11:"logFileName";s:0:"";s:9:"follow30x";s:1:"0";s:18:"makeDirectRequests";s:1:"0";s:16:"frontendBasePath";s:9:"/hostweb/";}',
			'dev_null_geshi' => 'a:0:{}',
			'devtools' => 'a:0:{}',
			'df_foundation5' => 'a:3:{s:21:"foundation_5_Magellan";s:1:"0";s:17:"foundation_5_Tabs";s:1:"0";s:19:"foundation_5_slider";s:1:"1";}',
			'feedit' => 'a:0:{}',
			'filemetadata' => 'a:0:{}',
			'google_auth' => 'a:19:{s:8:"enableFE";s:1:"1";s:8:"enableBE";s:1:"0";s:13:"enableProfile";s:1:"1";s:7:"authUrl";s:41:"https://accounts.google.com/o/oauth2/auth";s:9:"returnUrl";s:32:"http://{domain}/?type=1316773681";s:8:"finalUrl";s:16:"http://{domain}/";s:8:"errorUrl";s:31:"http://{domain}/loginError.html";s:15:"tokenRefreshUrl";s:42:"https://accounts.google.com/o/oauth2/token";s:8:"clientId";s:72:"893117143428-dpfsru1cj4u1o64gscager715leddi27.apps.googleusercontent.com";s:6:"secret";s:24:"VTfxqlEb4U2KP6372yundnyT";s:5:"scope";s:95:"https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email";s:6:"domain";s:9:"gmail.com";s:16:"addUsersToGroups";s:0:"";s:18:"addBeUsersToGroups";s:0:"";s:18:"createAdminBeUsers";s:1:"0";s:10:"storagePid";s:0:"";s:10:"recordType";s:36:"Tx_Extbase_Domain_Model_FrontendUser";s:22:"httpQueryNumericPrefix";s:0:"";s:26:"httpQueryArgumentSeparator";s:1:"&";}',
			'iconfont' => 'a:3:{s:8:"iconFont";s:11:"fontawesome";s:24:"customIconDefinitionFile";s:0:"";s:27:"enableHeaderRenderingOption";s:1:"0";}',
			'indexed_search' => 'a:18:{s:8:"pdftools";s:9:"/usr/bin/";s:8:"pdf_mode";s:2:"20";s:5:"unzip";s:9:"/usr/bin/";s:6:"catdoc";s:9:"/usr/bin/";s:6:"xlhtml";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:5:"unrtf";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:18:"fullTextDataLength";s:1:"0";s:23:"disableFrontendIndexing";s:1:"0";s:21:"enableMetaphoneSearch";s:1:"1";s:6:"minAge";s:2:"24";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:26:"useCrawlerForExternalFiles";s:1:"1";s:11:"flagBitMask";s:3:"192";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"1";}',
			'indexed_search_mysql' => 'a:0:{}',
			'less' => 'a:1:{s:7:"version";s:5:"0.4.0";}',
			'mediace' => 'a:0:{}',
			'metaseo' => 'a:4:{s:10:"enableBeta";s:0:"";s:23:"enableIntegrationTTNews";s:1:"1";s:29:"sitemap_clearCachePossibility";s:0:"";s:29:"sitemap_pageSitemapExpireDays";s:2:"60";}',
			'news' => 'a:17:{s:29:"removeListActionFromFlexforms";s:1:"2";s:20:"pageModuleFieldsNews";s:317:"LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:pagemodule_simple=title,datetime;LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:pagemodule_advanced=title,datetime,teaser,categories;LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:pagemodule_complex=title,datetime,teaser,categories,archive;";s:24:"pageModuleFieldsCategory";s:17:"title,description";s:11:"archiveDate";s:8:"datetime";s:13:"prependAtCopy";s:1:"1";s:6:"tagPid";s:2:"13";s:25:"showMediaDescriptionField";s:1:"0";s:12:"rteForTeaser";s:1:"0";s:22:"contentElementRelation";s:1:"1";s:13:"manualSorting";s:1:"0";s:19:"categoryRestriction";s:4:"none";s:34:"categoryBeGroupTceFormsRestriction";s:1:"0";s:6:"useFal";s:1:"1";s:12:"showImporter";s:1:"0";s:18:"storageUidImporter";s:2:"18";s:22:"resourceFolderImporter";s:12:"/news_import";s:24:"showAdministrationModule";s:1:"0";}',
			'news_ttnewsimport' => 'a:0:{}',
			'newsletter' => 'a:10:{s:11:"sender_name";s:4:"user";s:12:"sender_email";s:4:"user";s:18:"notification_email";s:4:"user";s:10:"fetch_path";s:0:"";s:10:"append_url";s:0:"";s:12:"path_to_lynx";s:13:"/usr/bin/lynx";s:17:"path_to_fetchmail";s:18:"/usr/bin/fetchmail";s:13:"keep_messages";s:1:"0";s:13:"attach_images";s:1:"1";s:15:"mails_per_round";s:3:"100";}',
			'nxtemplate' => 'a:0:{}',
			'openid' => 'a:0:{}',
			'powermail' => 'a:8:{s:12:"disableIpLog";s:1:"0";s:27:"disableMarketingInformation";s:1:"0";s:20:"disableBackendModule";s:1:"0";s:24:"disablePluginInformation";s:1:"0";s:13:"enableCaching";s:1:"0";s:28:"enableTableGarbageCollection";s:1:"0";s:15:"l10n_mode_merge";s:1:"0";s:29:"replaceIrreWithElementBrowser";s:1:"0";}',
			'realurl' => 'a:5:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'recycler' => 'a:0:{}',
			'rn_base' => 'a:11:{s:13:"verboseMayday";s:1:"0";s:11:"dieOnMayday";s:1:"1";s:21:"forceException4Mayday";s:1:"1";s:16:"exceptionHandler";s:0:"";s:20:"sendEmailOnException";s:0:"";s:9:"fromEmail";s:0:"";s:24:"send503HeaderOnException";s:1:"1";s:17:"loadHiddenObjects";s:1:"0";s:13:"activateCache";s:1:"0";s:18:"activateSubstCache";s:1:"0";s:8:"debugKey";s:0:"";}',
			'roq_newsevent' => 'a:0:{}',
			'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
			'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:1;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
			'scheduler' => 'a:4:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";}',
			'sourceopt' => 'a:0:{}',
			'static_info_tables' => 'a:2:{s:13:"enableManager";s:1:"0";s:5:"dummy";s:1:"0";}',
			'static_info_tables_de' => 'a:0:{}',
			'sys_action' => 'a:0:{}',
			't3_less' => 'a:0:{}',
			't3_tcpdf' => 'a:0:{}',
			't3socials' => 'a:0:{}',
			'taskcenter' => 'a:0:{}',
			'toctoc_comments' => 'a:13:{s:14:"donationSecret";s:0:"";s:11:"max_records";s:2:"10";s:9:"text_crop";s:2:"55";s:8:"show_sub";s:1:"1";s:10:"select_val";s:17:"5,10,20,30,50,100";s:10:"dnsbl_list";s:0:"";s:23:"importDataprefixtotable";s:1:"0";s:29:"updatefromRoottoCommentFolder";s:0:"";s:10:"updateMode";s:1:"0";s:9:"debugMode";s:1:"0";s:18:"delusers_firstname";s:7:"deleted";s:17:"delusers_lastname";s:4:"user";s:14:"delusers_email";s:20:"deleteduser@site.tld";}',
		),
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(
				'de',
			),
		),
	),
	'FE' => array(
		'debug' => FALSE,
		'loginSecurityLevel' => 'rsa',
	),
	'GFX' => array(
		'colorspace' => 'sRGB',
		'im' => 1,
		'im_mask_temp_ext_gif' => 1,
		'im_path' => '/usr/bin/',
		'im_path_lzw' => '/usr/bin/',
		'im_v5effects' => 1,
		'im_version_5' => 'im6',
		'image_processing' => 1,
		'jpg_quality' => '80',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'TYPO3\CMS\Install\Updates\BackendUserStartModuleUpdate' => 1,
			'TYPO3\CMS\Install\Updates\MigrateShortcutUrlsUpdate' => 1,
		),
	),
	'SYS' => array(
		'caching' => array(
			'cacheConfigurations' => array(
				'autoloader' => array(
					'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\SimpleFileBackend',
					'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\PhpFrontend',
					'groups' => array(
						'system',
					),
					'options' => array(
						'defaultLifetime' => 0,
					),
				),
				'extbase_object' => array(
					'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
					'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
					'groups' => array(
						'system',
					),
					'options' => array(
						'defaultLifetime' => 0,
					),
				),
			),
		),
		'clearCacheSystem' => '1',
		'devIPmask' => '',
		'displayErrors' => 0,
		'enableDeprecationLog' => FALSE,
		'encryptionKey' => 'c71643693fc1cc11dd3402cc236a03a6964486336b94a415c0078754930a639bda0310aa37f09aae7b12b2d3676e47ce',
		'isInitialInstallationInProgress' => FALSE,
		'sitename' => 'Loopshape CodeBase',
		'sqlDebug' => 0,
		'systemLogLevel' => 2,
		't3lib_cs_convMethod' => 'mbstring',
		't3lib_cs_utils' => 'mbstring',
		'trustedHostsPattern' => '.*\\.uberspace\\.de',
	),
);
?>